### ISSUE TITLE
Library not working

### ISSUE THREAD

**Issue by udhbhav** [mikeqfu/pydriosm#15] opened 2021-07-11 14:13 UTC
Hi,
I tried to install the library and use it. Looks like its broken. I did check on linux as well as mac. 
`>>> from pydriosm.downloader import GeofabrikDownloader
>>> geofabrik_downloader = GeofabrikDownloader()
>>> geofabrik_download_catalogue = geofabrik_downloader.get_download_catalogue()
>>> geofabrik_download_catalogue
>>> geofabrik_download_catalogue.columns.tolist()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute 'columns'`

**Comment by mikeqfu** [comment] 2021-07-11 15:22
Hi @udhbhav 

I tried to run on Windows the same lines as you posted:

```
>>> from pydriosm.downloader import GeofabrikDownloader
>>> geofabrik_downloader = GeofabrikDownloader()
>>> geofabrik_download_catalogue = geofabrik_downloader.get_download_catalogue()
>>> geofabrik_download_catalogue
                 Subregion  ...                                           .osm.bz2
0                  Algeria  ...  https://download.geofabrik.de/africa/algeria-l...
1                   Angola  ...  https://download.geofabrik.de/africa/angola-la...
2                    Benin  ...  https://download.geofabrik.de/africa/benin-lat...
3                 Botswana  ...  https://download.geofabrik.de/africa/botswana-...
4             Burkina Faso  ...  https://download.geofabrik.de/africa/burkina-f...
..                     ...  ...                                                ...
433  Australia and Oceania  ...  https://download.geofabrik.de/australia-oceani...
434        Central America  ...  https://download.geofabrik.de/central-america-...
435                 Europe  ...  https://download.geofabrik.de/europe-latest.os...
436          North America  ...  https://download.geofabrik.de/north-america-la...
437          South America  ...  https://download.geofabrik.de/south-america-la...
[438 rows x 6 columns]
>>> geofabrik_download_catalogue.columns.tolist()
['Subregion',
 'SubregionURL',
 '.osm.pbf',
 '.osm.pbf.Size',
 '.shp.zip',
 '.osm.bz2']
```

I didn't have any issues and couldn't reproduce the issue/error.  Did you install the package successfully? Can you provide more details about the steps you went through?

**Comment by udhbhav** [comment] 2021-07-12 07:25
I created a new environment and then installed pydriosm. It was showing some GDAL error. So, installed gdal from conda:

`
conda install -c conda-forge gdal
pip install --upgrade pydriosm
`
Also checked Pydriosm version on install using:
pydriosm.__version__

**Comment by mikeqfu** [comment] 2021-07-12 09:58
What error with GDAL did you get exactly? Were you on Windows or Linux? Does the [Installation](https://pydriosm.readthedocs.io/en/latest/installation.html) page of the package documentation provide any helpful information?

**Comment by mikeqfu** [comment] 2021-09-17 15:11
I assume the issue has been solved, in which case I shall close the issue.

**Closed by mikeqfu** 2021-09-17 15:11 UTC
